### ISSUE TITLE
Content for ticket blog post

### ISSUE THREAD

**Issue by EstiShay** [pycascades/www.pycascades.com#166]
_Please add this content to the body of the blog post in PR 161_

We've got more exciting news! [Tickets for PyCascades 2021 are now available on pretix](https://pretix.eu/pycascades/remote-2021/). Our ticket prices are $10 for students, $20 for individuals, and $50 for professional attendees.

Why should you get a ticket, you ask? Well, other than supporting our lovely little conference, we also have a special gift- you might remember these wonderful wooden badges from years past:
[insert photo of Nina & Thea's badges; it's in the mailchimp newsletter]
We will continue this tradition in 2021 and the first 150 ticket sales can sign up for our "PyCascades Attendee Kit" which comes with a customizable wooden badge and some additional surprises that you can show off on camera during the event 🥳. Where is the money going? The conference platform, equipment needed by staff and speakers to provide quality content, and all the tools we use to put on our regional conference. Head over to [pretix](https://pretix.eu/pycascades/remote-2021/) to get your ticket.

We realize that even these low ticket prices are a challenge for some folks right now, so keep an eye out for our financial aid announcements. The application will open in December.

**Program announcements coming soon**

Sponsors

We'd love your support of PyCascades. You can find more details on how to [become one of our wonderful sponsors on our website](https://2021.pycascades.com/become-a-sponsor/) or by reaching out to sponsorship@pycascades.com. 

Call for Volunteers

Just like last year, we have exciting volunteer opportunities for people interested in making this lovely conference happen! If you are interested in helping out, [visit our website to view the roles](https://2021.pycascades.com/volunteer). No prior experience needed and every little bit helps us keep this conference running smoothly, so sign up today!

As always, reach out to us at organizers@pycascades.com if you have any questions or concerns. Also, don't forget to subscribe to our newsletter to stay up-to-date on everything PyCascades (it's only important stuff, we promise)! https://2021.pycascades.com.

**Comment by roadsideseb** [comment]
I've updated the PR.
