### ISSUE TITLE
Two non-linking links on Code of Conduct page

### ISSUE THREAD

**Issue by li3n3** [pycascades/www.pycascades.com#7]
Looks like a couple links didn't get linkified on http://pycascades.readthedocs.io/code_of_conduct.html

> To help us respond in the best way to the situation, please follow the /code-of-conduct-reporting. The code of conduct representatives employ the /code-of-conduct-response to handle reports.

(If they're not supposed to be links, they'll need other instructions instead.)

**Comment by Mariatta** [comment]
Thanks for the report @li3n3 We'll look into this :smiley:

**Comment by Mariatta** [comment]
Thanks @li3n3. We have updated our code of conduct page. Please see: http://www.pycascades.com/conduct/
