### ISSUE TITLE
Update Grants page to reflect apps closed

### ISSUE THREAD

**Issue by EstiShay** [pycascades/www.pycascades.com#97]
The application period ended Nov. 22nd. Please update the website to reflect that applications have closed.
https://2020.pycascades.com/grants/

Specifically - 
Under the Grants header, please remove:
`Grant applications are now open. Use this form to apply for a grant.`
And replace it with:
`Our grant application period has closed.`

Under the Apply header, please remove:
`To apply for a grant please fill out this form. Please reach out to grants@pycascades.com if you have any questions or concerns.`
And replace it with:
`Our grant application period has closed.`

**Comment by roadsideseb** [comment]
Opened #99 to update the grants page.

**Comment by roadsideseb** [comment]
Resolved by #99
